### ISSUE TITLE
ValueError: shape mismatch in running the fit

### ISSUE THREAD

**Issue by bersavosh** [vosjo/speedyfit#10]
Thank you for the really helpful and nicely accessible package. I have been trying to run example cases (e.g., HIP 4618, or something else well observed and bright, e.g., Cyg X-1). The setup step (`speedyfit setup "Cyg_X-1" -grid kurucz --phot`) goes well and finds relevant measurements, etc. However, the fitting step fails:

```bash
speedyfit fit Cyg_X-1_setup_kurucz.yaml
.
.
.
  File "speedyfit/interpol.py", line 79, in create_pixeltypegrid
    pixelgrid[indices] = grid_data.T
ValueError: shape mismatch: value array of shape (615,19) could not be broadcast to indexing result of shape (3,615,8,3,19)
```

I'm running Speedyfit 0.2.3 (installed through pip) and Numpy 1.23.5 on Python 3.10.8.

Thanks for your help.

**Comment by vosjo** [comment]
Hi,

Thanks for reporting this issue.
I am currently on holiday. I will check it out on Wednesday and get back to
you.

Regards

**Comment by vosjo** [comment]
I have checked this. Seems to be an incompatibility with one of the newer releases of numpy. I will try to fix this. For now, if you want to use speedyfit, use an older numpy version. e.g. numpy==1.21.5 works.

**Comment by vosjo** [comment]
It should be solved. version 0.2.4 should work with numpy >= 1.23
Can you check if it works from your side?

**Comment by bersavosh** [comment]
Confirmed, it is resolved and the fit runs smoothly.

Thanks! :-)
