### ISSUE TITLE
"No models were accepted" issue

### ISSUE THREAD

**Issue by denizcdursun** [vosjo/speedyfit#11]
Hi @vosjo,

I get this error when I run your code for HIP 4648. Can you help me?

<img width="1151" alt="Ekran Resmi 2023-07-29 13 51 12" src="https://github.com/vosjo/speedyfit/assets/79997767/45648549-2dfd-419d-8931-02f15f7bc898">

**Comment by vosjo** [comment]
Hi, 
It looks like you have included GAIA3E measurements in the fit, but the kurucz tables that you want to use in the fit don't include this band. Can you try to add GAIA3E to 'photband_exclude' and see if the fit works then?

I will check if GAIA3E is missing from the kurucz grids that come with speedyfit. It is possible they are outdated, and that I have to update them.

**Comment by vosjo** [comment]
Can you also give me the output of
`speedyfit checkgrids`

And of
```
echo $SPEEDYFIT_MODELS
ls $SPEEDYFIT_MODELS
```

**Comment by denizcdursun** [comment]
Sure,

`speedyfit checkgrids`

<img width="1052" alt="Ekran Resmi 2023-08-01 10 11 53" src="https://github.com/vosjo/speedyfit/assets/79997767/dead8900-9e76-43f3-8df4-f61591070545">

```
echo $SPEEDYFIT_MODELS
ls $SPEEDYFIT_MODELS

```
<img width="901" alt="Ekran Resmi 2023-08-01 10 12 43" src="https://github.com/vosjo/speedyfit/assets/79997767/68883015-46f7-4abc-a755-2e1a5cc87016">

**Comment by denizcdursun** [comment]
if i run the fit, i get this now:

<img width="1056" alt="Ekran Resmi 2023-08-01 10 15 41" src="https://github.com/vosjo/speedyfit/assets/79997767/659f3880-a5ad-4fdb-aa09-0fb50b753d54">

my numpy version is 1.24.4

**Comment by denizcdursun** [comment]
hey there is good news,

I installed numpy1.20.1 version and as you said i deleted the Gaia3e mags. and it worked! 
Can you let us know when we can use Gaia3e?
