### ISSUE TITLE
How to download the SkyMapper survey photometry observation data

### ISSUE THREAD

**Issue by tpos8** [vosjo/speedyfit#13]
I am a new user of the SkyMapper, for my research, I want to download the SkyMapper photometry to Multiwave collect flux data and spectrum data. But I visited the SkyMapper "How to access" and I did not know how to download the data efficiently. So that, I need a help to download the data

**Comment by vosjo** [comment]
Hi, 
I am not sure if I understand your problem? I don't have any affiliation with skymapper. Speedyfit is just an SED fitting tool that can work with whatever data you provide. 
Are you failing to download skymapper photometry through the speedyfit interface? If so, please provide a bit more information about what you did and what error you got.

**Comment by tpos8** [comment]
hi，
I am so sorry about that, this my mistake to put this question in this.

**Comment by vosjo** [comment]
No problem. I hope you figure out how to obtain the skymapper photometry
you need!
