### ISSUE TITLE
How to fit binary sed

### ISSUE THREAD

**Issue by tpos8** [vosjo/speedyfit#14]
Hi,
I use the speedyfit to fit the sed for binary, but when I set the teff and teff2, rad and rad2, the  program output a error IndexError: list index out of range, so that how to set the binary parameter to fit this sed

**Comment by tpos8** [comment]
![00742367fbabf7f5d4a136b79a54bee](https://github.com/user-attachments/assets/c66a1392-5412-4e88-baf8-3df0993a0cd7)

**Comment by vosjo** [comment]
Hi,
Can you attach your input file?

**Comment by vosjo** [comment]
Closed due to not enough info to help.
