### ISSUE TITLE
Poor handling of path specified by SPEEDYFIT_MODELS environment variable

### ISSUE THREAD

**Issue by pmaxted** [vosjo/speedyfit#6]
It is unclear from the installation instructions that the environment variable SPEEDYFIT_MODELS must include the trailing "/" or "\"

Rather than fixing the documentation, it would be better to use os.path.join in the code to join filenames and paths correctly without the user needing to worry about trailing slashes, etc.

**Comment by vosjo** [comment]
The newest release fixes this problem.
